#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Install coding-agents-sentry-observability on this machine.

Usage:
  ./scripts/install.sh [options]

Options:
  --service             Install and start the macOS launchd background service.
  --dev                 Install development/test dependencies too.
  --dsn VALUE           Write VALUE as SENTRY_DSN in the generated config.
  --config FILE         Config file to create/update. Default: ~/.config/agent-vm-observability/env
  --venv DIR            Virtualenv directory. Default: ./.venv inside the repo.
  --force-config        Overwrite an existing config file.
  --dry-run             Print actions without making changes.
  -h, --help            Show this help.

Sentry is optional. Without SENTRY_DSN the bridge still records local memory
and the local dashboard works, but no traces are exported to Sentry.
EOF
}

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PYTHON_BIN="${PYTHON:-python3}"
VENV_DIR="${AGENT_VM_INSTALL_VENV:-$REPO_ROOT/.venv}"
CONFIG_FILE="${AGENT_VM_CONFIG:-$HOME/.config/agent-vm-observability/env}"
INSTALL_SERVICE=0
INSTALL_DEV=0
FORCE_CONFIG=0
DRY_RUN=0
SENTRY_DSN_VALUE="${SENTRY_DSN:-}"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --service)
      INSTALL_SERVICE=1
      shift
      ;;
    --dev)
      INSTALL_DEV=1
      shift
      ;;
    --dsn)
      if [[ $# -lt 2 ]]; then
        echo "--dsn requires a value" >&2
        exit 64
      fi
      SENTRY_DSN_VALUE="$2"
      shift 2
      ;;
    --config)
      if [[ $# -lt 2 ]]; then
        echo "--config requires a file path" >&2
        exit 64
      fi
      CONFIG_FILE="$2"
      shift 2
      ;;
    --venv)
      if [[ $# -lt 2 ]]; then
        echo "--venv requires a directory path" >&2
        exit 64
      fi
      VENV_DIR="$2"
      shift 2
      ;;
    --force-config)
      FORCE_CONFIG=1
      shift
      ;;
    --dry-run)
      DRY_RUN=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage >&2
      exit 64
      ;;
  esac
done

run() {
  if [[ "$DRY_RUN" -eq 1 ]]; then
    printf '+ '
    printf '%q ' "$@"
    printf '\n'
  else
    "$@"
  fi
}

write_config() {
  local config_dir
  config_dir="$(dirname "$CONFIG_FILE")"
  if [[ -f "$CONFIG_FILE" && "$FORCE_CONFIG" -ne 1 ]]; then
    echo "Keeping existing config: $CONFIG_FILE"
    echo "Use --force-config to rewrite it."
    return
  fi

  if [[ "$DRY_RUN" -eq 1 ]]; then
    echo "+ mkdir -p $config_dir"
    echo "+ write config $CONFIG_FILE"
    return
  fi

  mkdir -p "$config_dir"
  umask 077
  {
    cat <<EOF
# coding-agents-sentry-observability configuration
# Generated by scripts/install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)

# Optional: export traces to Sentry. Leave empty for local-only mode.
EOF
    if [[ -n "$SENTRY_DSN_VALUE" ]]; then
      printf 'SENTRY_DSN=%q\n' "$SENTRY_DSN_VALUE"
    else
      echo '# SENTRY_DSN='
    fi
    cat <<EOF
# Required only for `agent-vm sentry apply-dashboards`.
# SENTRY_ORG=your-sentry-org
SENTRY_PROJECT=agent-vm-usage

# Privacy: keep raw message/tool text out of Sentry and the local DB by default.
AGENT_VM_INCLUDE_TEXT=0
AGENT_VM_RECORD_MEMORY=1

# Runtime behavior.
AGENT_VM_POLL_SECONDS=15
AGENT_VM_MAX_BATCH=250

# Local state. Tilde expansion is supported for path-valued settings.
AGENT_VM_MEMORY_DB=~/.agent-vm-observability/memory.db
AGENT_VM_STATE=~/.local/state/agent-vm-observability/state.json

# Source locations. Uncomment to override auto-detected defaults.
# AGENT_VM_CODEX_LOGS_DB=$HOME/.codex/logs_2.sqlite
# AGENT_VM_CODEX_STATE_DB=$HOME/.codex/state_5.sqlite
# AGENT_VM_CLAUDE_GLOB=$HOME/.claude/projects/**/*.jsonl
EOF
  } > "$CONFIG_FILE"
  chmod 600 "$CONFIG_FILE"
  echo "Wrote config: $CONFIG_FILE"
}

if ! command -v "$PYTHON_BIN" >/dev/null 2>&1; then
  echo "Python not found: $PYTHON_BIN" >&2
  echo "Set PYTHON=/path/to/python3 or install Python 3.11+." >&2
  exit 69
fi

if ! "$PYTHON_BIN" - <<'PY' >/dev/null; then
import sys
raise SystemExit(0 if sys.version_info >= (3, 11) else 1)
PY
  PYTHON_VERSION="$($PYTHON_BIN - <<'PY'
import sys
print(f"{sys.version_info.major}.{sys.version_info.minor}")
PY
)"
  echo "Python 3.11+ is required; found $PYTHON_VERSION" >&2
  exit 69
fi

if [[ "$INSTALL_SERVICE" -eq 1 && "$(uname -s)" != "Darwin" ]]; then
  echo "--service currently supports macOS launchd only." >&2
  echo "Run the bridge manually with: $VENV_DIR/bin/agent-vm bridge --loop" >&2
  exit 69
fi

echo "Installing coding-agents-sentry-observability from: $REPO_ROOT"
echo "Virtualenv: $VENV_DIR"
echo "Config: $CONFIG_FILE"

run "$PYTHON_BIN" -m venv "$VENV_DIR"
run "$VENV_DIR/bin/python" -m pip install --upgrade pip
if [[ "$INSTALL_DEV" -eq 1 ]]; then
  run "$VENV_DIR/bin/python" -m pip install -e "$REPO_ROOT[dev]"
else
  run "$VENV_DIR/bin/python" -m pip install -e "$REPO_ROOT"
fi

write_config

if [[ "$DRY_RUN" -ne 1 ]]; then
  echo
  "$VENV_DIR/bin/agent-vm" status || true
fi

if [[ "$INSTALL_SERVICE" -eq 1 ]]; then
  run "$VENV_DIR/bin/agent-vm" install-launchd
fi

cat <<EOF

Done.

Next commands:
  source "$VENV_DIR/bin/activate"
  agent-vm bridge --once --backfill-minutes 30
  agent-vm dashboard --port 8765

For a persistent collector on macOS:
  ./scripts/install.sh --service

EOF
